version: '2.1'
orbs:
  node: circleci/node@5.1.0

defaults: &defaults
  docker:
    - image: cimg/python:3.10
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create and activate venv
    command: |
      # Verifica si el entorno virtual ya existe, y si no, lo crea
      if [ ! -d ~/project/venv ]; then
        python3 -m venv ~/project/venv
        echo "Entorno virtual creado"
      else
        echo "El entorno virtual ya existe"
      fi
      source ~/project/venv/bin/activate
      pip install --upgrade pip

jobs:
  deploy_app_to_railway:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project/
      - node/install:
          node-version: '20.9'
      - run: node --version
      - run:
          name: Setup Railway CLI
          command: |
            source ~/project/venv/bin/activate  # Activa el entorno virtual antes de instalar
            pip install railway
      - run:
          name: Deploy to Railway App
          command: |
            source ~/project/venv/bin/activate  # Activa el entorno virtual antes de desplegar
            cd bankchurn-api 
            railway login --token $RAILWAY_TOKEN
            railway up --service=NombreDelServicio
            railway up --detach

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - deploy_app_to_railway:
          filters:
            branches:
              only:
                - master